name = "choice-properties"
pages_build_output_dir = "."
compatibility_date = "2024-01-01"

[vars]
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
IMAGEKIT_URL = ""
IMAGEKIT_PUBLIC_KEY = ""
GEOAPIFY_API_KEY = ""
COMPANY_NAME = ""
COMPANY_EMAIL = ""
COMPANY_PHONE = ""
COMPANY_ADDRESS = ""
ADMIN_EMAILS = ""
